name: Trigger Update From Template

on:
  pull_request:
    branches:
      - master
    types:
      - closed

permissions:
  pull-requests: read

jobs:
  trigger-update-from-template:
    uses: infrastructure-blocks/trigger-update-from-template-workflow/.github/workflows/trigger-update-from-template.yml@v1
    secrets:
      github-pat: ${{ secrets.PAT }}
